### ISSUE TITLE
Structure of this git repository

### ISSUE THREAD

**Issue by mudrd8mz** [joshwillcock/Moodle-tool_completioncron#2]
To make direct installation from this Git repository into a Moodle site possible and easier, it is recommended that the root of the repository matches the root of the plugin itself. So the root repository should not contain the folder `completioncron` but there should be the contents of it. That way, it is possible to clone multiple plugins of the same type into one Moodle source code tree.

**Comment by joshwillcock** [comment]
This has been updated.
