### ISSUE TITLE
The project website does not exist

### ISSUE THREAD

**Issue by mudrd8mz** [joshwillcock/Moodle-tool_completioncron#3]
The plugin's record at https://moodle.org/plugins/view/tool_completioncron declares the project website to be http://joshwillcock.github.io/Moodle-Completion-Cron-Tool/ which does not seem to exist.

**Comment by joshwillcock** [comment]
Updated to: http://joshwillcock.github.io/Moodle-tool_completioncron/

The page changed when renaming project to Moodle naming convention for github
